basf/MolPipeline

molpipeline/mol2any/mol2rdkit_phys_chem.py
tests/test_elements/test_mol2any/test_mol2rdkit_phys_chem.py

Add a parameter fails_on_any_error to MolToRDKitPhysChem to get partial results when the computation of a single physchem descriptor fails.
This feature is necessary for data analysis, where we want to examine data even if one of 200 descriptors failed to be calculated.

mol2rdkit_phys_chem: make failure on any error optional

---

molpipeline/estimators/chemprop/featurizer_wrapper/__init__.py
molpipeline/estimators/chemprop/featurizer_wrapper/graph_wrapper.py
molpipeline/mol2any/mol2chemprop.py
requirements_chemprop.txt
test_extras/test_chemprop/test_chemprop_pipeline.py
test_extras/test_chemprop/test_models.py
test_extras/test_chemprop/test_neural_fingerprint.py

Adapts to ChemProp 2.0.3  
Requires ChemProp >= 2.0.3

Fix: moltochemprop not compatible with chemprop 2.0.3

---

.github/workflows/linting.yml

- Execute the unittests with the coverage module instead
of using the unittests module directly.
- Introduce a threshold for code coverage. If the coverage
will shrink below the threshold the CI/CD pipeline will
fail.
- Collect coverage separately for the core test suite and
extra packages like chemprop.

.github: add test coverage with threshold

---

molpipeline/mol2any/mol2concatinated_vector.py
molpipeline/utils/subpipeline.py
tests/test_elements/test_mol2any/test_mol2concatenated.py
tests/test_utils/test_subpipeline.py

This PR provides some new utils functionality for automatically extracting specific subpipelines from a given Pipeline and added additional functions to mol2concatinated_vector

utils/mol2concatinated_vector: changes for xai

---

.github/workflows/linting.yml

Due to the delayed rdkti release we had to pin the pandas version. Since rdkit is now updated, this can be removed.

remove pandas version fix

---

molpipeline/mol2any/mol2rdkit_phys_chem.py
pyproject.toml

This is only temporally, as long [fp_density](https://github.com/rdkit/rdkit/blame/db0e71bc1c002fa1f0fdc4f678488b6d1464d7aa/rdkit/Chem/Descriptors.py#L202) is using deprecated code.

Block logs for physchem descriptors

---

molpipeline/mol2any/mol2bool.py
tests/test_elements/test_mol2any/test_mol2bool.py

- Add new MolToBool element that converts values to
a bool array. Can be used for masking.

mol2any: add mol2bool element

---

.github/workflows/linting.yml

- Add package source directory to the coverage call.
Otherwise completely untested files not called in
the unittests would slip through CI/CD pipeline.
- Now completely untested files will be in the
coverage report with 0% coverage.

github: add package source dir to coverage

---

molpipeline/abstract_pipeline_elements/core.py
molpipeline/abstract_pipeline_elements/mol2any/mol2bitvector.py
molpipeline/abstract_pipeline_elements/mol2any/mol2floatvector.py
molpipeline/any2mol/bin2mol.py
molpipeline/any2mol/sdf2mol.py
molpipeline/any2mol/smiles2mol.py
molpipeline/error_handling.py
molpipeline/mol2any/mol2bin.py
molpipeline/mol2any/mol2bool.py
molpipeline/mol2any/mol2concatinated_vector.py
molpipeline/mol2any/mol2inchi.py
molpipeline/mol2any/mol2maccs_key_fingerprint.py
molpipeline/mol2any/mol2morgan_fingerprint.py
molpipeline/mol2any/mol2net_charge.py
molpipeline/mol2any/mol2path_fingerprint.py
molpipeline/mol2any/mol2rdkit_phys_chem.py
molpipeline/mol2any/mol2smiles.py
molpipeline/mol2mol/filter.py
molpipeline/mol2mol/reaction.py
molpipeline/mol2mol/scaffolds.py
molpipeline/mol2mol/standardization.py
molpipeline/pipeline/_molpipeline.py
tests/utils/mock_element.py

Init refactoring

---

molpipeline/estimators/chemprop/models.py
molpipeline/pipeline/_molpipeline.py
test_extras/test_chemprop/test_chemprop_pipeline.py
test_extras/test_chemprop/test_models.py
tests/test_elements/test_error_handling.py

Fixes an error that MolSanitizeErrors are caught but not treated correctly by ErrorHandling
- fixes one line of code (replace wrong return)
- adds a dummy test for checking
- automatic isort on some other files

Error handling sanitize bug

---

molpipeline/mol2any/mol2morgan_fingerprint.py
tests/test_elements/test_mol2any/test_mol2morgan_fingerprint.py

- _explain_rdmol generated a sparse fingeprint not considering folding of the fingerprint. This led to GetBitInfoMap to return indices corresponding to the non-folded fingerprint. These indices lead to out-of-bounds errors for folded dense fingerprints.
- Fixed this by generating a dense fingerprint in the _explain_rdmol function.
- This fix is needed for the explainability module.

mol2morgan_fingerprint: fix bug of mismatched indices after folding

---

molpipeline/utils/comparison.py
tests/test_utils/test_comparison.py
tests/utils/default_models.py

Pipeline Elements may contain dicts which are not param-dicts. These may not necessarily have str values as keys, breaking the split method. This PR checks if the dict has str-keys prior to spliting the str.

102 bug remove irrelevant params fails for int vaules

---

molpipeline/abstract_pipeline_elements/mol2any/mol2bitvector.py
molpipeline/abstract_pipeline_elements/mol2any/mol2floatvector.py
molpipeline/mol2any/mol2concatinated_vector.py
molpipeline/mol2any/mol2maccs_key_fingerprint.py
molpipeline/mol2any/mol2morgan_fingerprint.py
molpipeline/mol2any/mol2net_charge.py
molpipeline/mol2any/mol2path_fingerprint.py
molpipeline/mol2any/mol2rdkit_phys_chem.py
tests/test_elements/test_mol2any/test_mol2concatenated.py
tests/test_elements/test_mol2any/test_mol2maccs_key_fingerprint.py
tests/test_elements/test_mol2any/test_mol2morgan_fingerprint.py
tests/test_elements/test_mol2any/test_mol2path_fingerprint.py
tests/utils/logging.py

- Feature names could not be extracted from fingerprint pipeline elements.
- Added common interface to get names for fingerprints and descriptors.

mol2any: get feature names from elements

---

molpipeline/pipeline/_molpipeline.py

The object _MolPipeline has a property called `raise_nones`. This is legacy property and can be reomved.  See related [issue](https://github.com/basf/MolPipeline/issues/128)

remove raise_nones

---

molpipeline/abstract_pipeline_elements/mol2any/mol2bitvector.py
molpipeline/estimators/chemprop/neural_fingerprint.py
test_extras/test_chemprop/test_neural_fingerprint.py
tests/test_elements/test_mol2any/test_mol2morgan_fingerprint.py

Solves https://github.com/basf/MolPipeline/issues/130
ToDos:

130 add fix attribute output type

---

molpipeline/estimators/chemprop/neural_fingerprint.py
test_extras/test_chemprop/chemprop_test_utils/default_models.py
test_extras/test_chemprop/test_neural_fingerprint.py

This PR fixes the failing initialization of the NeuralFP with kwags, described in this [issue](https://github.com/basf/MolPipeline/issues)
**Problem:**
The error is caused by setting `disable_fitting` after calling `super().__init__`, which requires  `disable_fitting` to be defined. Move setting of parameter before initialization
**ToDos:**

Fix: kwargs fails for Neural Fingerprint

---

molpipeline/mol2mol/filter.py
tests/test_elements/test_mol2mol/test_mol2mol_filter.py

**Reason**
This issue solves the bug described in this [issue](https://github.com/basf/MolPipeline/issues/138).  
**Solution:**
Cast keys to int.
ToDos:

Fix bug: ElementFilter: roundtrip from recursive_to_json to recursive_from_json messes up atom types

---

requirements.txt

setuptools  should not longer be a requirement for molipeline.
ToDo:

remove setuptools from requirements

---

molpipeline/mol2any/mol2rdkit_phys_chem.py
tests/test_elements/test_mol2any/test_mol2rdkit_phys_chem.py

Empty descriptor list would lead to unusable MolToRDKitPhysChem. Now, if an empty list is given it's replaced by the default descriptor list.

rdkit_phys_chem: set empty descriptor list to default list

---

molpipeline/any2mol/sdf2mol.py
tests/test_elements/test_any2mol/test_sdf2mol.py

Properties defined in the SDF were discarded. Now they are kept and stored in the molecule data structures.

sdf2mol: keep properties from file and add tests

---

tests/test_elements/test_mol2mol/test_mol2mol_filter.py

Adapt Unittests to new RDKit SMILES + Linting

---

.github/workflows/linting.yml

We only want to support the latest three Python version (3.11, 3.12, 3.12). Therefore, the test with Python 3.10 is dropped.

remove support for Python 3.10: remove Python 3.10 tests
